apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: ldapidp 
    mappingMethod: claim 
    type: LDAP
    ldap:
      attributes:
        id: 
        - dn
        email: 
        - mail
        name: 
        - cn
        preferredUsername: 
        - sAMAccountName
      bindDN: "CN=svc_webupdate,OU=Users,OU=Service,DC=corp,DC=domain,DC=ru" 
      bindPassword: 
        name: ldap-secret
      insecure: true
      url: "ldap://adtest1.corp.domain.ru/OU=Users,OU=gk,DC=corp,DC=domain,DC=ru?sAMAccountName(&(objectclass=*)(|(memberOf=CN=nix_adm,OU=Groups,OU=gk,DC=corp,DC=domain,DC=ru)(memberOf=CN=medvedev_a,OU=Users,OU=ITLab,OU=gk,DC=corp,DC=domain,DC=ru)))"
      