#rsyslogd Facilities
auth / authpriv #Messages related to authentication.
cron #Messages generated by the crond service.
daemon #Generic facility that can be used for nonspecified daemons.
kern #Kernel messages.
lpr #Messages generated through the legacy lpd print system.
mail #Email-related messages.
mark #Special facility that can be used to write a marker periodically.
news #Messages generated by the NNTP news system.
security #Same as auth / authpriv. Should not be used anymore.
syslog #Messages generated by the syslog system.
user #Messages generated in user space.
uucp #Messages generated by the legacy UUCP system.
local0-7 #Messages generated by services that are configured by any of the local0 through local7 facilities.

#rsyslogd Priorities
debug #Debug messages that will give as much information as possible about service operation.
info #Informational messages about normal service operation.
notice #Used for informational messages about items that might become an issue later.
warning / warn #Something is suboptimal, but there is no real error yet.
err /error #A noncritical error has occurred.
crit #A critical error has occurred.
alert #Used when the availability of the service is about to be discontinued.
emerg / panic #Message generated when the availability of the service is discontinued.

#To send messages(logs) to remote server from network programs(nginx, haproxy, apache)
#nginx
vi /etc/nginx/nginx.conf
access_log syslog:server=10.8.182.203:514,facility=local7,tag=nginx,severity=info;
