language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt --extra-index-url file://$PWD/lib --upgrade  --ignore-installed six
  - pip install -r test-requirements.txt
# command to run tests
script:
  - pycodestyle samples tests
  - pytest
