apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ds # pod name
  namespace: default
  labels:
    usecase: loadbalancer
spec:
  selector:
    matchLabels:
        usecase: loadbalancer
  template:
    metadata:
      labels:
        usecase: loadbalancer
    spec:
      nodeSelector: # starts pod only on node with below labels (usecase=loadbalancer)
        usecase: loadbalancer
      # tolerations:
      # # this toleration is to have the daemonset runnable on master nodes
      # # remove it if your masters can't run pods
      # - key: node-role.kubernetes.io/master
      #   operator: Exists
      #   effect: NoSchedule
      containers:
      - name: ex12
        image: nginx
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
      #   volumeMounts:
      #   - name: varlog
      #     mountPath: /var/log
      #   - name: varlibdockercontainers
      #     mountPath: /var/lib/docker/containers
      #     readOnly: true
      # terminationGracePeriodSeconds: 30
      # volumes:
      # - name: varlog
      #   hostPath:
      #     path: /var/log
      # - name: varlibdockercontainers
      #   hostPath:
      #     path: /var/lib/docker/containers
