---
- name: Update all packages on hosts.
  hosts: sp
  #hosts: localhost
  vars_files:
    # - /usr/git/work/ansible/vaulted_vars.yml
    - /usr/git/work/ansible/vars/entrance-vars.yml
    #remote_user: local
  remote_user: krasnosvarov_dn
  become: true
  become_user: root
  become_method: sudo
  
  tasks:
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
