---
all:
  test:
    test-vm ansible_ssh_host=10.9.32.10:
      
  arm_journal:
    ansible_ssh_host=10.5.10.147:
    v00esbrejapp02	ansible_ssh_host=10.5.10.148:
    v00esbrejhz01	ansible_ssh_host=10.5.10.149:
    v00esbrejhz02	ansible_ssh_host=10.5.10.150:
    v00esbrejhz03	ansible_ssh_host=10.5.10.151:
    tc:
      v00rep-sp01tc	ansible_ssh_host=10.5.10.154:
      v00rep-sp02tc	ansible_ssh_host=10.5.10.155:
    haproxy:
      v00esbrejnlb01	ansible_ssh_host=10.5.10.152:
      v00esbrejnlb02	ansible_ssh_host=10.5.10.153:
      v00repsp01nlb	ansible_ssh_host=10.5.10.156:
    v00rep-sp01ora	ansible_ssh_host=10.5.10.157:
