---
- name: Execute a script.
  hosts: test2
  remote_user: local
  become: yes
  tasks:
    #- name: Transfer the script
      #copy: src=/usr/git/work/scripts/audit_security.sh dest=/home/local mode=0777
    #- name: Execute the script
    #  shell: "sh /home/local/audit_security.sh"
    - name: whoami
      shell: "whoami"
