---
- hosts: 127.0.0.1
  connection: local
      #  ansible_python_interpreter: "{{ansible_playbook_python}}"
  # vars: 
  #   ansible_python_interpreter: "/usr/bin/python3"
  roles:
    - setup_terraform


#apply
#ansible-playbook ansible/create_terraform.yml --extra-vars="application=Ptst terra_dir=terraform service_account_passw=" -v
#destroy
#ansible-playbook ansible/create_terraform.yml --extra-vars="application=Ptst terra_dir=terraform_test service_account_passw= DESTROY=destroy" -v
